---

- hosts: all
  become: yes
  become_method: sudo
   
  tasks:

  - name: Read variables
    include_vars: '{{ item }}'
    with_first_found:
      - files:
          - "{{ inventory_hostname }}.yml"
          - "default_keys.yml"
        paths: "./var/"

  - name: Deploy SSH-Keys to remote host
    authorized_key:
      user: pi
      key: "{{ keystodeploy|map(attribute='sshkey')|join('\n') }}"
      exclusive: true
  - name: Deploy SSH-Keys to remote host
    authorized_key:
      user: ansible-func
      key: "{{ keystodeploy|map(attribute='sshkey')|join('\n') }}"
      exclusive: true
